spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/anon
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012


upload:
  path: C:/profile_upload